/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import clases.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author jonat
 */
public class frmPet extends javax.swing.JFrame {
    LinkedList<clsDog>dogObjectList = new LinkedList<>();
     LinkedList<clsCat>catObjectList = new LinkedList<>();

    /**
     * Creates new form frmPet
     */
    public frmPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlanelGeneral = new javax.swing.JPanel();
        PetManager = new javax.swing.JTabbedPane();
        Petlist = new javax.swing.JPanel();
        List = new javax.swing.JScrollPane();
        PetList = new javax.swing.JList<>();
        CatManager = new javax.swing.JPanel();
        CodeCat = new javax.swing.JLabel();
        txtcodecat = new javax.swing.JTextField();
        SepaCodeCat = new javax.swing.JSeparator();
        BronYearCat = new javax.swing.JLabel();
        txtBronYearCat = new javax.swing.JTextField();
        SepaBronYearCat = new javax.swing.JSeparator();
        NameCat = new javax.swing.JLabel();
        txtNamecat = new javax.swing.JTextField();
        SepaNameCat = new javax.swing.JSeparator();
        ColorCat = new javax.swing.JLabel();
        txtColorcat = new javax.swing.JTextField();
        SepaColorCat = new javax.swing.JSeparator();
        HealthStatusCat = new javax.swing.JLabel();
        CbHealthStatusCat = new javax.swing.JComboBox<>();
        SepaHealthStatusCat = new javax.swing.JSeparator();
        BreedCat = new javax.swing.JLabel();
        CbBreedCat = new javax.swing.JComboBox<>();
        SepaBreedCat = new javax.swing.JSeparator();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        DogManager = new javax.swing.JPanel();
        CodeDog = new javax.swing.JLabel();
        txtcodeDog = new javax.swing.JTextField();
        SepaCodeDog = new javax.swing.JSeparator();
        BronYearDog = new javax.swing.JLabel();
        txtBronYearDog = new javax.swing.JTextField();
        SepaBronYearDog = new javax.swing.JSeparator();
        NameDog = new javax.swing.JLabel();
        txtNameDog = new javax.swing.JTextField();
        SepaNameDog = new javax.swing.JSeparator();
        ColorDog = new javax.swing.JLabel();
        txtColorDog = new javax.swing.JTextField();
        SepaColorDog = new javax.swing.JSeparator();
        HealthStatusDog = new javax.swing.JLabel();
        CbHealthStatusDog = new javax.swing.JComboBox<>();
        SepaHealthStatusDog = new javax.swing.JSeparator();
        BreedDog = new javax.swing.JLabel();
        CbBreedDog = new javax.swing.JComboBox<>();
        SepaBreedDog = new javax.swing.JSeparator();
        agregar1 = new javax.swing.JButton();
        modificar1 = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        nuevo1 = new javax.swing.JButton();
        ChekPedigreeDog = new javax.swing.JCheckBox();
        PanelSuperior = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));

        PlanelGeneral.setPreferredSize(new java.awt.Dimension(600, 450));
        PlanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PetManager.setBackground(new java.awt.Color(102, 102, 102));
        PetManager.setForeground(new java.awt.Color(255, 255, 255));
        PetManager.setToolTipText("");
        PetManager.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        Petlist.setBackground(new java.awt.Color(204, 204, 204));
        Petlist.setForeground(new java.awt.Color(255, 255, 255));

        PetList.setBackground(new java.awt.Color(102, 102, 102));
        PetList.setForeground(new java.awt.Color(255, 255, 255));
        PetList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pet ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        List.setViewportView(PetList);

        javax.swing.GroupLayout PetlistLayout = new javax.swing.GroupLayout(Petlist);
        Petlist.setLayout(PetlistLayout);
        PetlistLayout.setHorizontalGroup(
            PetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        PetlistLayout.setVerticalGroup(
            PetlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        PetManager.addTab("Pet List", Petlist);

        CatManager.setBackground(new java.awt.Color(204, 204, 204));

        CodeCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CodeCat.setText("Code");

        SepaCodeCat.setForeground(new java.awt.Color(51, 51, 51));

        BronYearCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BronYearCat.setText("Bron Year");

        SepaBronYearCat.setForeground(new java.awt.Color(51, 51, 51));

        NameCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        NameCat.setText("Name");

        txtNamecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamecatActionPerformed(evt);
            }
        });

        SepaNameCat.setForeground(new java.awt.Color(51, 51, 51));

        ColorCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ColorCat.setText("Color");

        SepaColorCat.setForeground(new java.awt.Color(51, 51, 51));

        HealthStatusCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        HealthStatusCat.setText("Health Status");

        CbHealthStatusCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CbHealthStatusCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo", "Critico", "Muerto" }));

        SepaHealthStatusCat.setForeground(new java.awt.Color(51, 51, 51));

        BreedCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BreedCat.setText("Breed");

        CbBreedCat.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CbBreedCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siamés", "Persa", "Bengalí", "Abisinio", "Azul RusoRagDoll", "Javanès" }));

        SepaBreedCat.setForeground(new java.awt.Color(51, 51, 51));

        agregar.setBackground(new java.awt.Color(102, 102, 102));
        agregar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("AGREGAR");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarMouseExited(evt);
            }
        });
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(102, 102, 102));
        modificar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("MODIFICAR");
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarMouseExited(evt);
            }
        });
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(102, 102, 102));
        eliminar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("ELIMINAR");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarMouseExited(evt);
            }
        });
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        nuevo.setBackground(new java.awt.Color(102, 102, 102));
        nuevo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo.setText("NUEVO");
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoMouseExited(evt);
            }
        });
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CatManagerLayout = new javax.swing.GroupLayout(CatManager);
        CatManager.setLayout(CatManagerLayout);
        CatManagerLayout.setHorizontalGroup(
            CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatManagerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addComponent(SepaHealthStatusCat)
                        .addGap(43, 43, 43))
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SepaCodeCat)
                                .addComponent(SepaBronYearCat)
                                .addGroup(CatManagerLayout.createSequentialGroup()
                                    .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CatManagerLayout.createSequentialGroup()
                                            .addComponent(CodeCat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtcodecat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(CatManagerLayout.createSequentialGroup()
                                            .addComponent(BronYearCat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                            .addComponent(txtBronYearCat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(24, 24, 24)))
                            .addGroup(CatManagerLayout.createSequentialGroup()
                                .addComponent(HealthStatusCat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbHealthStatusCat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CatManagerLayout.createSequentialGroup()
                                .addComponent(ColorCat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtColorcat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(CatManagerLayout.createSequentialGroup()
                                .addComponent(NameCat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(txtNamecat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addComponent(SepaColorCat)
                            .addComponent(SepaNameCat))
                        .addGap(74, 74, 74))
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CatManagerLayout.createSequentialGroup()
                                .addComponent(BreedCat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbBreedCat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SepaBreedCat, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
            .addGroup(CatManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        CatManagerLayout.setVerticalGroup(
            CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatManagerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodeCat)
                            .addComponent(txtcodecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaCodeCat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameCat)
                            .addComponent(txtNamecat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaNameCat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BronYearCat)
                            .addComponent(txtBronYearCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaBronYearCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ColorCat)
                            .addComponent(txtColorcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaColorCat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HealthStatusCat)
                            .addComponent(CbHealthStatusCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaHealthStatusCat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CatManagerLayout.createSequentialGroup()
                        .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BreedCat)
                            .addComponent(CbBreedCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaBreedCat, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(CatManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        PetManager.addTab("Cat Manager", CatManager);

        DogManager.setBackground(new java.awt.Color(204, 204, 204));

        CodeDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CodeDog.setText("Code");

        txtcodeDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        SepaCodeDog.setForeground(new java.awt.Color(51, 51, 51));

        BronYearDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BronYearDog.setText("Bron Year");

        txtBronYearDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        SepaBronYearDog.setForeground(new java.awt.Color(51, 51, 51));

        NameDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        NameDog.setText("Name");

        txtNameDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtNameDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDogActionPerformed(evt);
            }
        });

        SepaNameDog.setForeground(new java.awt.Color(51, 51, 51));

        ColorDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ColorDog.setText("Color");

        txtColorDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        SepaColorDog.setForeground(new java.awt.Color(51, 51, 51));

        HealthStatusDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        HealthStatusDog.setText("Health Status");

        CbHealthStatusDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CbHealthStatusDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo", "Critico", "Muerto" }));

        SepaHealthStatusDog.setForeground(new java.awt.Color(51, 51, 51));

        BreedDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        BreedDog.setText("Breed");

        CbBreedDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CbBreedDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Affenpinscher", "Afgano", "Akita japonés", "Basenji", "Basset Azul de Gascuña", "Galgo italiano", "Shiba Inu", "Pomeriana", "Cocker Spaniel", "Bulldog francés", "Beagle" }));

        SepaBreedDog.setForeground(new java.awt.Color(51, 51, 51));

        agregar1.setBackground(new java.awt.Color(102, 102, 102));
        agregar1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        agregar1.setForeground(new java.awt.Color(255, 255, 255));
        agregar1.setText("AGREGAR");
        agregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregar1MouseExited(evt);
            }
        });
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });

        modificar1.setBackground(new java.awt.Color(102, 102, 102));
        modificar1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        modificar1.setForeground(new java.awt.Color(255, 255, 255));
        modificar1.setText("MODIFICAR");
        modificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificar1MouseExited(evt);
            }
        });
        modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar1ActionPerformed(evt);
            }
        });

        eliminar1.setBackground(new java.awt.Color(102, 102, 102));
        eliminar1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        eliminar1.setForeground(new java.awt.Color(255, 255, 255));
        eliminar1.setText("ELIMINAR");
        eliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar1MouseExited(evt);
            }
        });
        eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar1ActionPerformed(evt);
            }
        });

        nuevo1.setBackground(new java.awt.Color(102, 102, 102));
        nuevo1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nuevo1.setForeground(new java.awt.Color(255, 255, 255));
        nuevo1.setText("NUEVO");
        nuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nuevo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevo1MouseExited(evt);
            }
        });
        nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo1ActionPerformed(evt);
            }
        });

        ChekPedigreeDog.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ChekPedigreeDog.setText("Pedigree");
        ChekPedigreeDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekPedigreeDogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DogManagerLayout = new javax.swing.GroupLayout(DogManager);
        DogManager.setLayout(DogManagerLayout);
        DogManagerLayout.setHorizontalGroup(
            DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DogManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(DogManagerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addComponent(SepaHealthStatusDog)
                        .addGap(43, 43, 43))
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SepaCodeDog)
                                .addComponent(SepaBronYearDog)
                                .addGroup(DogManagerLayout.createSequentialGroup()
                                    .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DogManagerLayout.createSequentialGroup()
                                            .addComponent(CodeDog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtcodeDog, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DogManagerLayout.createSequentialGroup()
                                            .addComponent(BronYearDog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                            .addComponent(txtBronYearDog, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(24, 24, 24)))
                            .addGroup(DogManagerLayout.createSequentialGroup()
                                .addComponent(HealthStatusDog, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbHealthStatusDog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DogManagerLayout.createSequentialGroup()
                                .addComponent(ColorDog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtColorDog, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(DogManagerLayout.createSequentialGroup()
                                .addComponent(NameDog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(txtNameDog, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addComponent(SepaColorDog)
                            .addComponent(SepaNameDog))
                        .addGap(74, 74, 74))
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DogManagerLayout.createSequentialGroup()
                                .addComponent(BreedDog, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbBreedDog, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ChekPedigreeDog, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SepaBreedDog, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        DogManagerLayout.setVerticalGroup(
            DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DogManagerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodeDog)
                            .addComponent(txtcodeDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaCodeDog, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameDog)
                            .addComponent(txtNameDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaNameDog, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BronYearDog)
                            .addComponent(txtBronYearDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaBronYearDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ColorDog)
                            .addComponent(txtColorDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaColorDog, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HealthStatusDog)
                            .addComponent(CbHealthStatusDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaHealthStatusDog, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DogManagerLayout.createSequentialGroup()
                        .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BreedDog)
                            .addComponent(CbBreedDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChekPedigreeDog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SepaBreedDog, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(DogManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        PetManager.addTab("Dog Manager", DogManager);

        PlanelGeneral.add(PetManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 602, 420));

        PanelSuperior.setBackground(new java.awt.Color(102, 102, 102));

        Titulo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Pet Manager");

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        PlanelGeneral.add(PanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PlanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PlanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamecatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamecatActionPerformed

    private void agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseEntered
        //agregar.setBackground(white);
        //agregar.setForeground(black);
    }//GEN-LAST:event_agregarMouseEntered

    private void agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseExited
        //agregar.setBackground(black);
        //agregar.setForeground(white);
    }//GEN-LAST:event_agregarMouseExited

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
       
        try{
            String code = txtcodecat.getText();
            String name = txtNamecat.getText();
            String color = txtColorcat.getText();
            int bornYear = Integer.parseInt(txtBronYearCat.getText());
            String breed = CbBreedCat.getSelectedItem().toString();
            String healtStatus = CbHealthStatusCat.getSelectedItem().toString();
            
            
            if(code.equals("")||name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this,"Registro Guardado");
            }else{
                clsCat Cat = new clsCat(code,name,bornYear,color,healtStatus,breed);
                        catObjectList.add(Cat);
                        this.FillJListCat();
                        JOptionPane.showMessageDialog(this,"Registro Guardado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
   
    }//GEN-LAST:event_agregarActionPerformed

    private void modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseEntered
        //modificar.setBackground(white);
        //modificar.setForeground(black);
    }//GEN-LAST:event_modificarMouseEntered

    private void modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseExited
        //modificar.setBackground(black);
        //modificar.setForeground(white);
    }//GEN-LAST:event_modificarMouseExited

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        //modificar();
        //modificar2();
        //listar();
        //Nuevo();
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseEntered
        //eliminar.setBackground(white);
        //eliminar.setForeground(black);
    }//GEN-LAST:event_eliminarMouseEntered

    private void eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseExited
        //eliminar.setBackground(black);
        //eliminar.setForeground(white);
    }//GEN-LAST:event_eliminarMouseExited

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        //eliminar();
        //eliminar2();
        //listar();
        //Nuevo();
    }//GEN-LAST:event_eliminarActionPerformed

    private void nuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseEntered
        //nuevo.setBackground(white);
        //nuevo.setForeground(black);
    }//GEN-LAST:event_nuevoMouseEntered

    private void nuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseExited
        //nuevo.setBackground(black);
        //nuevo.setForeground(white);
    }//GEN-LAST:event_nuevoMouseExited

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void txtNameDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDogActionPerformed

    private void agregar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar1MouseEntered

    private void agregar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar1MouseExited

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        try{
            String code = txtcodeDog.getText();
            String name = txtNameDog.getText();
            String color = txtColorDog.getText();
            int bornYear = Integer.parseInt(txtBronYearDog.getText());
            String breed = CbBreedDog.getSelectedItem().toString();
            String healtStatus = CbHealthStatusDog.getSelectedItem().toString();
            boolean pedigree = ChekPedigreeDog.isSelected();
            
            
            if(code.equals("")||name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this,"Registro Guardado");
            }else{
                clsDog Dog = new clsDog(code,name,bornYear,color,healtStatus,breed,pedigree);
                        dogObjectList.add(Dog);
                        this.FillJListDog();
                        JOptionPane.showMessageDialog(this,"Registro Guardado");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
    }//GEN-LAST:event_agregar1ActionPerformed

    private void modificar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar1MouseEntered

    private void modificar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar1MouseExited

    private void modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar1ActionPerformed

    private void eliminar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1MouseEntered

    private void eliminar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1MouseExited

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void nuevo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo1MouseEntered

    private void nuevo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo1MouseExited

    private void nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo1ActionPerformed

    private void ChekPedigreeDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekPedigreeDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChekPedigreeDogActionPerformed

    
    private void FillJListCat(){
            DefaultListModel model = new DefaultListModel();
            int index = 0;
            for (clsCat cat:catObjectList ){
                String data = cat.getName() + "  -  "+cat.getBreed()+"  - Gato";
                model.add(index, data);
                index++;
            }
            PetList.setModel(model);
        }
    
    private void FillJListDog(){
            DefaultListModel model = new DefaultListModel();
            int index = 0;
            for (clsDog dog:dogObjectList ){
                String data = dog.getName() + "  -  "+dog.getBreed()+"  - Perro";
                model.add(index, data);
                index++;
            }
            PetList.setModel(model);
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BreedCat;
    private javax.swing.JLabel BreedDog;
    private javax.swing.JLabel BronYearCat;
    private javax.swing.JLabel BronYearDog;
    private javax.swing.JPanel CatManager;
    private javax.swing.JComboBox<String> CbBreedCat;
    private javax.swing.JComboBox<String> CbBreedDog;
    private javax.swing.JComboBox<String> CbHealthStatusCat;
    private javax.swing.JComboBox<String> CbHealthStatusDog;
    private javax.swing.JCheckBox ChekPedigreeDog;
    private javax.swing.JLabel CodeCat;
    private javax.swing.JLabel CodeDog;
    private javax.swing.JLabel ColorCat;
    private javax.swing.JLabel ColorDog;
    private javax.swing.JPanel DogManager;
    private javax.swing.JLabel HealthStatusCat;
    private javax.swing.JLabel HealthStatusDog;
    private javax.swing.JScrollPane List;
    private javax.swing.JLabel NameCat;
    private javax.swing.JLabel NameDog;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JList<String> PetList;
    private javax.swing.JTabbedPane PetManager;
    private javax.swing.JPanel Petlist;
    private javax.swing.JPanel PlanelGeneral;
    private javax.swing.JSeparator SepaBreedCat;
    private javax.swing.JSeparator SepaBreedDog;
    private javax.swing.JSeparator SepaBronYearCat;
    private javax.swing.JSeparator SepaBronYearDog;
    private javax.swing.JSeparator SepaCodeCat;
    private javax.swing.JSeparator SepaCodeDog;
    private javax.swing.JSeparator SepaColorCat;
    private javax.swing.JSeparator SepaColorDog;
    private javax.swing.JSeparator SepaHealthStatusCat;
    private javax.swing.JSeparator SepaHealthStatusDog;
    private javax.swing.JSeparator SepaNameCat;
    private javax.swing.JSeparator SepaNameDog;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar1;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton modificar1;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton nuevo1;
    private javax.swing.JTextField txtBronYearCat;
    private javax.swing.JTextField txtBronYearDog;
    private javax.swing.JTextField txtColorDog;
    private javax.swing.JTextField txtColorcat;
    private javax.swing.JTextField txtNameDog;
    private javax.swing.JTextField txtNamecat;
    private javax.swing.JTextField txtcodeDog;
    private javax.swing.JTextField txtcodecat;
    // End of variables declaration//GEN-END:variables
}
